name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Requirements
      run:
        sudo apt update
        sudo apt install autoconf libtool libconfig-dev libreadline-dev
    - name: Dependencies
      run: bash ./make.sh
    - name: Build
      run: make
      working-directory: keybow
